# Generated by Django 3.2.6 on 2021-08-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='number',
        ),
    ]
