# Generated by Django 3.2.6 on 2021-08-16 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_auto_20210814_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCEL', 'Cancel'), ('PENDING_PAYMENT', 'Pending Payment'), ('ON_HOLD', 'On Hold'), ('WAITING_FOR_PAYMENT', 'Waiting For Payment'), ('PROCESSING', 'Processing'), ('DONE', 'Done')], default='PENDING_PAYMENT', max_length=220),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
