# Generated by Django 3.2.6 on 2021-08-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('TVS', 'TVS'), ('Hero', 'Hero'), ('Yamaha', 'TVS'), ('Minister', 'Minister'), ('Walton', 'Walton'), ('Suzuki', 'Suzuki')], max_length=220, null=True),
        ),
    ]
