# Generated by Django 3.2.6 on 2021-08-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order_customer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_type',
            new_name='customerType',
        ),
    ]
