# Generated by Django 3.2.6 on 2021-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_customer_type_order_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerType',
            field=models.CharField(blank=True, choices=[('Ordinary', 'Ordinary'), ('Police', 'Police'), ('RAB', 'RAB'), ('DGIF', 'DGIF'), ('CID', 'CID'), ('NAVY', 'NAVY'), ('Air Force', 'Air Force'), ('Army', 'Army'), ('DB', 'DB'), ('Administration', 'Administration')], default='Ordinary', max_length=200, null=True),
        ),
    ]
