# Generated by Django 3.2.6 on 2021-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_order_customertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
