# Generated by Django 3.2.6 on 2021-08-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_product_brandimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isStorm',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
