# Generated by Django 3.2.6 on 2021-08-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_product_isstorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isStorm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
