# Generated by Django 3.2.6 on 2021-08-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_product_isstorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('CANCEL', 'Cancel'), ('PENDING_PAYMENT', 'Pending Payment'), ('ON_HOLD', 'On Hold'), ('WAITING_FOR_PAYMENT', 'Waiting For Payment'), ('PROCESSING', 'Processing'), ('DONE', 'Done')], default='ON_HOLD', max_length=220, null=True),
        ),
    ]
