# Generated by Django 3.2.6 on 2021-09-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210906_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
