# Generated by Django 3.2.6 on 2021-09-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='user',
        ),
        migrations.AlterField(
            model_name='confirm',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
