# Generated by Django 3.2.6 on 2021-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
