# Generated by Django 3.2.6 on 2021-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
