# Generated by Django 3.2.6 on 2021-09-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_test_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.DeleteModel(
            name='Confirm',
        ),
    ]
