# Generated by Django 3.2.6 on 2021-09-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210906_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='test',
            name='email',
        ),
    ]
