# Generated by Django 3.2.6 on 2021-09-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_test_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='full_name',
            new_name='comment',
        ),
    ]
