# Generated by Django 3.2.6 on 2021-09-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_rename_note_paymentverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentverification',
            old_name='comment',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
