# Generated by Django 3.2.6 on 2021-09-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20210906_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverification',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
