# Generated by Django 3.2.6 on 2021-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_paymentverification_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverification',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
