# Generated by Django 3.2.6 on 2021-09-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_paymentverification_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverification',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='order_number',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
