# Generated by Django 3.2.6 on 2021-09-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_order_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barcode',
        ),
    ]
