# Generated by Django 3.2.6 on 2021-09-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_paymentverification_nid_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentverification',
            old_name='nid_number',
            new_name='account_number',
        ),
    ]
