# Generated by Django 3.2.6 on 2021-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_rename_nid_number_paymentverification_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
